# Generated by Django 3.0.4 on 2020-04-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0004_auto_20200414_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceticket',
            name='proposal',
        ),
        migrations.CreateModel(
            name='ProposalChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('priority', models.IntegerField(null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus_engine.Proposal')),
            ],
        ),
        migrations.AddField(
            model_name='choiceticket',
            name='proposal_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus_engine.ProposalChoice'),
        ),
    ]
