# Generated by Django 3.0.4 on 2020-04-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0005_auto_20200414_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceticket',
            name='proposal_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus_engine.ProposalChoice'),
        ),
    ]
