# Generated by Django 3.0.4 on 2020-04-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0006_auto_20200414_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceticket',
            name='choice_value',
        ),
    ]
