# Generated by Django 3.0.4 on 2020-04-14 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consensus_engine', '0007_remove_choiceticket_choice_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentChoiceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus_engine.ChoiceTicket')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus_engine.Proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
