# Generated by Django 3.0.4 on 2020-04-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0008_currentchoiceticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
