# Generated by Django 3.0.4 on 2020-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0009_proposal_proposal_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_caption',
            field=models.CharField(max_length=200),
        ),
    ]
