# Generated by Django 3.0.4 on 2020-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0010_auto_20200417_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalchoice',
            name='actived_date',
            field=models.DateTimeField(null=True, verbose_name='active date'),
        ),
        migrations.AddField(
            model_name='proposalchoice',
            name='deactivated_date',
            field=models.DateTimeField(null=True, verbose_name='deactivated date'),
        ),
    ]
