# Generated by Django 3.0.4 on 2020-04-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0011_auto_20200421_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalchoice',
            old_name='actived_date',
            new_name='activated_date',
        ),
    ]
