# Generated by Django 3.0.4 on 2020-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0013_proposal_owned_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
            ],
        ),
    ]
