# Generated by Django 3.0.4 on 2020-04-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0014_proposalgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consensus_engine.ProposalGroup'),
        ),
    ]
