# Generated by Django 3.0.4 on 2020-04-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0016_proposalgroup_owned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='proposal_caption',
            new_name='proposal_description',
        ),
        migrations.AddField(
            model_name='proposalgroup',
            name='group_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
