# Generated by Django 3.0.4 on 2020-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0017_auto_20200427_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceticket',
            name='current',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
