# Generated by Django 3.0.4 on 2020-06-01 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0020_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 10, 26, 17, 472973, tzinfo=utc), verbose_name='date joined'),
            preserve_default=False,
        ),
    ]
