# Generated by Django 3.0.4 on 2020-06-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0021_groupmembership_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='current_consensus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='do_not_use', to='consensus_engine.ProposalChoice'),
        ),
    ]
