# Generated by Django 3.0.4 on 2020-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0025_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='date_accepted_or_declined',
            field=models.DateTimeField(null=True, verbose_name='date accepted or declined'),
        ),
    ]
