# Generated by Django 3.0.4 on 2020-06-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0026_groupinvite_date_accepted_or_declined'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(verbose_name='snapshot date')),
                ('consensus_data', models.TextField()),
                ('consensus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus_engine.ProposalChoice')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus_engine.Proposal')),
            ],
        ),
    ]
