# Generated by Django 3.0.4 on 2020-06-30 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0027_consensushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consensushistory',
            name='consensus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consensus_engine.ProposalChoice'),
        ),
    ]
