# Generated by Django 3.0.4 on 2020-07-14 11:00

import consensus_engine.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0028_auto_20200630_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='state',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'TRIAL'), (2, 'PUBLISHED'), (3, 'ON_HOLD'), (4, 'ARCHIVED')], default=consensus_engine.utils.ProposalState['DRAFT']),
        ),
    ]
