# Generated by Django 3.0.4 on 2020-10-12 13:42

import consensus_engine.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0029_proposal_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceticket',
            name='state',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'TRIAL'), (2, 'PUBLISHED'), (3, 'ON_HOLD'), (4, 'ARCHIVED')], default=consensus_engine.utils.ProposalState['PUBLISHED']),
        ),
    ]
