# Generated by Django 3.0.4 on 2020-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0030_choiceticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='can_trial',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='can_trial',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
