# Generated by Django 3.0.4 on 2020-11-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus_engine', '0031_auto_20201015_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalgroup',
            name='group_default_choices',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
